language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: puja7D/Z3dtZllM0FLqmZlbLL7Inr3Jowci7ZclLnd6xJmd0JlJfj9CuAAFfvaj7J64Ua0vL1j8b+w8cKubOidaSXPn1yTaGqF3MQTMzgqDZjOa7QVU0fwYDHyIrsHoYA0GIV9jeyS7rDyhxtoTmKoE7khU7rxKAcRw61qYyoKHpgreTIBrkXFoTMOuvebtMGPCMqJT9Y8QhCCtvxYwuYYaiRyMrs5xeI4VGAq3VcGpZ4kxdfh07VBgijPghAIjdaJckfogk6G1augUv42mfg5IWjD4AZ0Y2RULtWn1Ds6EsgjPhvLR2iOen57DQG7H9Sl20jJmtyFHbsZXdFD03cbNbgjfJN9aG/yD/1ZzzNf4YPpdWJTEtGa78OPjq5J/9XyOigkFBiG4mnA6y96JihpDHE8sggMwP+tdCjoegH4+n44lho7jEtSogzgd7GEBst444pGCX8wOHcKGm7caPInwRWG43u7osikgOdA1NB3ZXfjo2L6scofiiEY5l9RdaRk2cbgM5/6S2gu7DtlbArJ+Klo6JoiVnXkQUsypEOhiUAXCycW7mXQJOmGDrHo0GG7d7jxW1NXI3ILk+FiW4qobKg0nVMAiPFDhCHh55Ppo4NH4P9w8i6jbVIbl1VeOsXuQ8mEZEM29AkWYzKuICfofU5XU02p4nYuKwHPWuFWM=
  app: https://git.heroku.com/safe-retreat-73506.git
  on:
    repo: KatelinDeSerano/node-shopping-list-integration-tests
